version: "3.7"

services:
  loki:
    image: grafana/loki:2.4.1
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:2.4.1
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yaml
    volumes:
      - ./config/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./vols/logs:/root/logs

  grafana:
    image: grafana/grafana:8.3.2
    restart: unless-stopped
    user: "0"
    volumes:
      - ./vols/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
